
// Product based
export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const CATEGORIES_ERROR = "CATEGORIES_ERROR";

// Cart Data
export const SET_CART_DATA = "SET_CART_DATA";
export const CART_FETCH_FAILURE = "CART_FETCH_FAILURE";
export const CART_FETCH_LOADING = "CART_FETCH_LOADING";
export const SET_CART_TOTAL_COST = "SET_CART_TOTAL_COST";
export const SET_CART_TOTAL_ITEMS = "SET_CART_TOTAL_ITEMS";
// export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
// export const ITEM_ADD_CART_FAILED = "ITEM_ADD_CART_FAILED";
// export const ITEM_ADD_CART_SUCCESS = "ITEM_ADD_CART_SUCCESS";


// Login and user Profile
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const DELETE_USER_PROFILE = "DELETE_USER_PROFILE";
export const LOGIN_FAILURE_STATUS = "LOGIN_FAILURE_STATUS";
export const LOGIN_FETCH_LOADING = "LOGIN_FETCH_LOADING";